# Generated by Django 4.2.1 on 2023-05-08 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=10)),
                ('octave', models.PositiveIntegerField()),
                ('time', models.PositiveIntegerField()),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='MusicWallet.bar')),
            ],
        ),
        migrations.CreateModel(
            name='SharpNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicWallet.note')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.IntegerField()),
                ('time_signature_top', models.IntegerField()),
                ('time_signature_bottom', models.IntegerField()),
                ('clef', models.TextField(choices=[('G_CLEF', 'G'), ('C_CLEF', 'C'), ('F_CLEF', 'F')])),
                ('sharps', models.ManyToManyField(related_name='songs', through='MusicWallet.SharpNote', to='MusicWallet.note')),
            ],
        ),
        migrations.AddField(
            model_name='sharpnote',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicWallet.song'),
        ),
        migrations.AddField(
            model_name='bar',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bars', to='MusicWallet.song'),
        ),
    ]
